"""empty message

Revision ID: 1416662b2576
Revises: 4f00e2c6c570
Create Date: 2014-07-15 12:31:12.142894

"""

# revision identifiers, used by Alembic.
revision = '1416662b2576'
down_revision = '4f00e2c6c570'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('hello', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'hello')
    ### end Alembic commands ###
