"""empty message

Revision ID: 1b8914f87961
Revises: 2790378dc2aa
Create Date: 2014-07-15 12:26:02.517029

"""

# revision identifiers, used by Alembic.
revision = '1b8914f87961'
down_revision = '2790378dc2aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('derp', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'derp')
    ### end Alembic commands ###
