"""empty message

Revision ID: 1e164d61d3ab
Revises: 1416662b2576
Create Date: 2014-07-15 12:33:21.469558

"""

# revision identifiers, used by Alembic.
revision = '1e164d61d3ab'
down_revision = '1416662b2576'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', u'hello')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column(u'hello', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
