"""empty message

Revision ID: 2790378dc2aa
Revises: None
Create Date: 2014-07-15 11:49:01.761989

"""

# revision identifiers, used by Alembic.
revision = '2790378dc2aa'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
