"""empty message

Revision ID: 3c3f515a65de
Revises: None
Create Date: 2014-07-15 15:13:05.884347

"""

# revision identifiers, used by Alembic.
revision = '3c3f515a65de'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_number', sa.String(length=30), nullable=True),
    sa.Column('from_number', sa.String(length=30), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('time_sent', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
