"""empty message

Revision ID: 42bc721a87f8
Revises: 1e164d61d3ab
Create Date: 2014-07-15 12:55:52.159732

"""

# revision identifiers, used by Alembic.
revision = '42bc721a87f8'
down_revision = '1e164d61d3ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time_sent', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'time_sent')
    ### end Alembic commands ###
