"""empty message

Revision ID: 4a446c9fadb0
Revises: 42bc721a87f8
Create Date: 2014-07-15 14:48:29.671290

"""

# revision identifiers, used by Alembic.
revision = '4a446c9fadb0'
down_revision = '42bc721a87f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
