"""empty message

Revision ID: 4f00e2c6c570
Revises: e8311523d0e
Create Date: 2014-07-15 12:28:24.287669

"""

# revision identifiers, used by Alembic.
revision = '4f00e2c6c570'
down_revision = 'e8311523d0e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', u'derpy')
    op.drop_column('messages', u'derp')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column(u'derp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column(u'derpy', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
