"""empty message

Revision ID: e8311523d0e
Revises: 1b8914f87961
Create Date: 2014-07-15 12:27:39.948969

"""

# revision identifiers, used by Alembic.
revision = 'e8311523d0e'
down_revision = '1b8914f87961'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('derpy', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'derpy')
    ### end Alembic commands ###
